stages:
  - build
  - release

build-release:
  stage: build
  image: gitlab-registry.cern.ch/swan/docker-images/builder
  script:
    - echo "Building css"
    - yarn build
  cache:
    key: "$CI_PIPELINE_ID"
    paths:
      - ./
  tags:
    - docker

release-version:
  stage: release
  script:
    - echo "Releasing $CI_COMMIT_TAG"
    - rm -rf ./css/lesshat ./css/*.less  .gitlab-ci.yml .gitignore .git node_modules package.json yarn.lock README.md
  cache:
    key: "$CI_PIPELINE_ID"
    paths:
      - ./
  artifacts:
    name: $CI_COMMIT_TAG
    paths:
      - ./*
    expire_in: 48 weeks
  only: 
      - /^v.*$/
